In [2]:
import numpy as np

In [3]:
brain_cell = np.random.rand(2,2)
print(brain_cell)

[[0.68143043 0.82195796]
 [0.82951674 0.74024314]]


In [4]:
brain_connection = np.random.rand(2,2,4)# f is for the connection
print(brain_connection)

[[[0.75161437 0.60977504 0.541109   0.33960174]
  [0.17282579 0.69478837 0.37419358 0.12861478]]

 [[0.5262179  0.87067886 0.3919037  0.75532026]
  [0.28113245 0.01574896 0.80516226 0.97610443]]]


In [5]:
def compress(total_sum,inputnodecount):
    actual_val = total_sum/inputnodecount
    return actual_val

In [6]:
def connector(input_weights,adjust_amount):
    output = sum(input_weights)

    output = compress(output,len(input_weights))

    if output>adjust_amount :
        return adjust_amount
    else:
        return 0
        